name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 11 * * *' # Runs at 9:30 PM AEST (11:30 AM UTC) every day

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        # Fetch data from ArcGIS
        curl -L 'https://spatial-gis.information.qld.gov.au/arcgis/rest/services/QWise/CrocodileSightingsPublicView/FeatureServer/30/query?where=sighttime+%3E+CURRENT_TIMESTAMP+-+INTERVAL+%271%27+DAY&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=*&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=%7B+%22wkid%22%3A4326+%7D&havingClause=&gdbVersion=&historicMoment=&returnDistinctValues=false&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&multipatchOption=xyFootprint&resultOffset=&resultRecordCount=&returnTrueCurves=false&returnExceededLimitFeatures=false&quantizationParameters=&returnCentroid=false&timeReferenceUnknownClient=false&sqlFormat=none&resultType=&featureEncoding=esriDefault&datumTransformation=&f=geojson' \
           | jq '.features' > sightings.json
        # Prepend FeatureCollection
        jq -s '{"type": "FeatureCollection", "name": "Koala sightings", "features": .}' sightings.json > koala-sightings.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add koala-sightings.json
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
